language: java,node_js
jdk:
  - oraclejdk8
node_js:
  - "7.10"
services:
  - mongodb
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true

before_script:
  -cd src/main/resources/client && npm install -g @angular/cli && cd ../../../../

script:
  -mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
  -cd src/main/resources/client && ng build --prod