language: java
jdk:
  - oraclejdk8
services:
  - mongodb
sudo: required
env:
  - NODE_VERSION="7.10"
before_install:
  - nvm install $NODE_VERSION
install: true
before_script:
  - travis_wait 45 mvn install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true
  - cd src/main/resources/client && npm install -g @angular/cli
script:
  - ng build --prod
  - cd ../../../../ && mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
