language: java
jdk:
  - oraclejdk8
node_js:
  - "7.10"
services:
  - mongodb
sudo: required
install: true
before_script:
  -cd src/main/resources/client && npm install -g @angular/cli
script:
  -mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
  -cd src/main//resources/client && ng build --prod
