language: java
jdk:
  - oraclejdk8
services:
  - docker
sudo: required
env:
  - NODE_VERSION="7.10"
before_install:
  - nvm install $NODE_VERSION
install: true

before_script:
  - docker pull mysql
  - docker run -p 3306:3306  -e MYSQL_DATABASE=ticket_service MYSQL_ROOT_PASSWORD=1234 -d mysql:latest
  -
  - npm install -g @angular/cli@1.6.5
  - cd $TRAVIS_BUILD_DIR/ticket-service-frontend/angular/ && npm install
script:
  - ng build
  - cd $TRAVIS_BUILD_DIR/ticket-service-backend && mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'

after_success:
  - mvn clean test jacoco:report coveralls:report
