spring:
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ticket_service?useSSL=false
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
token:
  cookie-name: auth
  secret: MY_SECRET_TSS
registration-codes:
#next fields are equal to role names in db
  organizer: organizer123